apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: elasticsearch-exporter
  name: elasticsearch-exporter
  namespace: monitoring
spec:
  ports:
  - name: es-metrics
    port: 9108
    targetPort: es-metrics
  selector:
    k8s-app: elasticsearch-exporter
