apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: ups-exporter
  name: ups-exporter
  namespace: monitoring
subsets:
- addresses:
  - ip: 192.168.1.62
  ports:
  - name: metrics
    port: 9099
    protocol: TCP
