{{- if .Values.armExporter.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: arm-exporter
  name: arm-exporter
spec:
  selector:
    matchLabels:
      k8s-app: arm-exporter
  template:
    metadata:
      labels:
        k8s-app: arm-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm
                - arm64
      containers:
      - command:
        - /bin/rpi_exporter
        - --web.listen-address=127.0.0.1:{{ .Values.armExporter.service.port }}
        image: {{ .Values.armExporter.image.repository }}:{{ .Values.armExporter.image.tag }}
        imagePullPolicy: {{ .Values.armExporter.image.pullPolicy }}
        name: arm-exporter
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          privileged: true
      - args:
        - --secure-listen-address=$(IP):{{ .Values.armExporter.service.port }}
        - --upstream=http://127.0.0.1:{{ .Values.armExporter.service.port }}/
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        env:
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: carlosedp/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: {{ .Values.armExporter.service.port }}
          hostPort: {{ .Values.armExporter.service.port }}
          name: https
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      serviceAccountName: arm-exporter
      tolerations:
      - operator: Exists
{{- end }}
