{{- if .Values.elasticExporter.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: elasticsearch-exporter
  name: elasticsearch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-exporter
    spec:
      containers:
      - command:
        - /bin/elasticsearch_exporter
        - -es.uri=http://elasticsearch.logging.svc:9200
        - -es.timeout=60s
        - -es.all=true
        image: carlosedp/elasticsearch-exporter:1.0.4rc1
        livenessProbe:
          httpGet:
            path: /health
            port: 9108
          initialDelaySeconds: 30
          timeoutSeconds: 10
        name: elasticsearch-exporter
        ports:
        - containerPort: 9108
          name: es-metrics
        readinessProbe:
          httpGet:
            path: /health
            port: 9108
          initialDelaySeconds: 30
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi
        securityContext:
          capabilities:
            drop:
            - SETPCAP
            - MKNOD
            - AUDIT_WRITE
            - CHOWN
            - NET_RAW
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
          runAsNonRoot: true
          runAsUser: 1000
      restartPolicy: Always
{{- end }}
